server:
  port: 8090

spring:
  application:
    name: bff-service
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "${ALLOWED_ORIGINS:http://mypolicy-web-231893203344-us-east-1-an.s3-website-us-east-1.amazonaws.com}"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000
        loggerLevel: BASIC

logging:
  level:
    com.mypolicy.bff: DEBUG
    feign: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

eureka:
  client:
    service-url:
      defaultZone: http://mypolicy-alb-1359684399.us-east-1.elb.amazonaws.com/eureka/
  instance:
    prefer-ip-address: true