server:
  port: 8090

spring:
  config:
    import: optional:configserver:http://admin:config123@config-service:8888
  application:
    name: bff-service

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

logging:
  level:
    com.mypolicy.bff: DEBUG

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://discovery-service:8761/eureka}
  instance:
    prefer-ip-address: true
    ip-address: ${EUREKA_INSTANCE_IP:}
    instance-id: ${EUREKA_INSTANCE_IP:localhost}:${server.port}